kind = "web"
previewPath = "/"
title = "POINT CLIM"
version = "1.0.0"
id = "artifacts/point-clim"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25681

[services.development]
run = "pnpm --filter @workspace/point-clim run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/point-clim", "run", "build" ]
publicDir = "artifacts/point-clim/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25681"
BASE_PATH = "/"
